---
# ansible-playbook ec2_facts.yml --vault-password-file vault_pass
#
# AWS tasks for some group of hosts creation, and could be used for playing different tasks on it
# AWS Keys should be provided in vault - secret.yml
# - aws_owner is undefined by default and should be added into the vault - secret.yml
# - tagName is test by default and should be changed accordingly
# - role_name is dummy default and should be changed accordingly

- hosts: localhost
  tasks:
    - name: Get ec2 facts
      ec2_instance_facts:
        filters:
          "tag:Name": test
          instance-state-name: running
      register: ec2_facts

    - name: Print facts
      debug:
        msg: "{{ ec2_facts.instances }}"

    - name: Add instances Public IPs to host group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groupname: servers
      with_items: "{{ ec2_facts.instances }}"


- name: Group based tasks
  hosts: servers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - role_name
