---
- name: Update cache
  apt:
    update_cache: yes

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  register: apt_upgrade

- name: Install prerequisite packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - python-pip
    - vim
    - nano
