---
# Ansible issue with draining healthy targets - https://github.com/ansible/ansible/pull/39715
# Ansible issue with custom health_check_path - https://github.com/ansible/ansible/issues/50024
- name: Create a Target group for {{ container_name }} service
  elb_target_group:
    name: "{{ ecs_cluster_name }}-{{ container_name }}-target-group"
    protocol: http
    port: "{{ container_port }}"
    vpc_id: "{{ ecs_vpc.vpcs[0].vpc_id }}"
    health_check_path: "{{ healthcheck }}"
    successful_response_codes: "200,250-260"
    target_type: instance
    state: present
    wait_timeout: 600
    wait: True
  register: ecs_tg
  when:
    - ecs_state == "present"
    - ecs_alb == true
